### PR TITLE
Add Gherkin grammar support

### PR DESCRIPTION
**Pull request by jhansche**
This resolves Glavin001/atom-beautify#377

Uses the https://github.com/cucumber/gherkin/tree/master/js node.js
package to use the official Lexer class.

The only known issue I've seen so far is that it does not format
tables properly -- the columns are not resized to match the widest
cell in each column.

### CODE REVIEW

**Comment by meustice** [comment]
@Glavin001 When can we expect v0.29.0 with Gherkin support?  very excited about this update!  :+1:

**Comment by Glavin001** [comment]
This is great! Thank you for this Pull Request. Only thing that is missing is tests: place `original` and `expected` files in a `gherkin` directory inside of `examples/nested-jsbeautifyrc/` directory: https://github.com/Glavin001/atom-beautify/tree/master/examples/nested-jsbeautifyrc
Thanks again!

@meustice I hope to merge this soon. I have been set back with v0.29.0 because of work and I do not have the time that I would like to review all of the Pull Requests properly and add new features under the v0.29.0 milestone. Hopefully this week goes well and I have a little bit of time this weekend to review and merge everything.
If the tests are all there, I would like to merge all of the currently open Pull Requests and then make a new release.
Thank you for your patience!

**Comment by jhansche** [comment]
@Glavin001 thanks, I'll see if I can get around to writing tests for this, and I'll make the change for `debug_lexer` also. The main reason I didn't want it to run initially is that it could slow things down if it's executed when it's not needed.  Is there a Logger method to check if a certain type is enabled, before doing the rest of the work?  I.e., only do the work if log level is verbose?

**Comment by Glavin001** [comment]
>  Is there a Logger method to check if a certain type is enabled, before doing the rest of the work? I.e., only do the work if log level is verbose?

Good idea. You could probably do something like:

```coffeescript
loggerLevel = atom?.config.get('atom-beautify._loggerLevel') 
if loggerLevel is 'verbose':
  # Log stuff here
```

>  I'll see if I can get around to writing tests for this, and I'll make the change for debug_lexer also. 

The tests should be very easy: an example file with some styling problems in the `original` directory, and then the correctly styled output in the `expected` directory. You can disable a test by adding `_` to the front of the filename inside of `original`. The `_` prefix in the `original` example file will cause it to be ignored / skipped. So if you could add a completely working test and then maybe a disabled test for the tables, then that would be great! Should only take a few minutes. Just something rough. Thanks!

**Comment by jhansche** [comment]
@Glavin001 Are the existing test failures expected?  When I run `build-package.sh`, I get a bunch of failures:

    Finished in 4.637 seconds
    55 tests, 395 assertions, 201 failures, 0 skipped

**Comment by jhansche** [comment]
@Glavin001 I ran into an issue with Atom automatically inserting a newline at the end of the file upon saving (due to the `whitespace` package).  This was causing problems because atom-beautify appears to specifically strip the trailing newlines from resolved string, as even trying to explicitly add a call to `@write_blank()`, or concatenating `\n` to the resolved string, and the test continued to fail due to the trailing newline in the expected output.

The only way to get the tests to pass was by turning off the "ensure newline" option from the whitespace package, so that I could delete the trailing newline from the original and expected files.  Then it would work.

Is that a known issue?  Anything I should have done differently to account for that?

**Comment by Glavin001** [comment]
> The only way to get the tests to pass was by turning off the "ensure newline" option from the whitespace package, so that I could delete the trailing newline from the original and expected files. Then it would work.
> 
> Is that a known issue? Anything I should have done differently to account for that?

Nope, you are correct. Disabling the `whitespace` package, at least temporarily, if also what I do. Alternatively you could use the Right-Click context menu item for the file in the file tree called `Beautify File` which will not trigger the `whitespace` package.

**Comment by Glavin001** [comment]
> Are the existing test failures expected? When I run build-package.sh, I get a bunch of failures:

These failures are likely because there are many beautifiers supported that use third-party CLI executables that need to be installed. For instance, to run the tests for beautifying PHP code Atom Beautify requires PHP-CS-Fixer, which I assume you may not have installed. As long as your tests for Gherkin pass, then I can review this and still merge it. Thanks.

**Comment by Glavin001** [comment]
Published to v0.28.9

**Pull request merged**
