### PR TITLE
use tidy-markdown 2.0.3 explicitly

### PR DESCRIPTION
**Pull request by bbodenmiller**
Because 2.0.5 is broken

Related to #1549

### CODE REVIEW

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by AStupidBear** [comment]
@Glavin001 Can you tag a new release? I'm having the same issue and I want to stick with tidy-markdown.

**Comment by Glavin001** [comment]
Published to v0.29.19

**Comment by AStupidBear** [comment]
@Glavin001 Thanks!

**Pull request merged**
