### PR TITLE
Correspondence to PHP-CS-Fixer v2

### PR DESCRIPTION
**Pull request by onigra**
### What does this implement/fix? Explain your changes.

Correspondence to PHP-CS-Fixer v2.

### Does this close any currently open issues?

#1465 

### Any other comments?

- This is breaking change for PHP. 💥 
- This PR is subject to #1510 merged.

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by cahya6d6d6e** [comment]
why is this still not implemented?

**Comment by Glavin001** [comment]
I just finished my final exams yesterday. I should now have time to revisit working on Atom-Beautify and review and merge these Pull Requests. Thank you for your patience!

**Comment by Glavin001** [comment]
Is it reasonable to expect all PHP-CS-Fixer users to upgrade to 2.x? Since this PR is a breaking change for PHP-CS-Fixer 1.x users, maybe we should add two separate beautifiers? PHP-CS-Fixer (original) and PHP-CS-Fixer2 (new, from this PR). Then make PHP-CS-Fixer (1) the default and users can opt-in to PHP-CS-Fixer2 when they are ready. Thoughts? I personally do not use PHP-CS-Fixer, so this would be for your fellow PHP developers advantage so I will leave the decision up to you 😃 .

**Comment by cahya6d6d6e** [comment]
backward compatibility for older PHP-CS-Fixers sounds like a good idea

**Comment by Glavin001** [comment]
Thanks for contributing!

**Comment by Glavin001** [comment]
Published to v0.29.19

**Pull request merged**
