### PR TITLE
Push request for issue #559

### PR DESCRIPTION
**Pull request by prettydiff**

### CODE REVIEW

**Comment by Glavin001** [comment]
Thank you!

**Comment by Glavin001** [comment]
Published to v0.28.13

**Comment by Glavin001** [comment]
The example files should be files nested in the directories `expected` and `original`, not files named `expected` and `original`.

**Comment by prettydiff** [comment]
I see you have already fixed this.  Thanks for letting me so that I can get this correct on the next pull request.

**Comment by Glavin001** [comment]
Yup just wanted to let you know :smile:.

I am cleaning up errors showing in CI runs. This will help merging Pull Requests, since I can just look at the commit status.

**Pull request merged**
