### PR TITLE
Update to Prettydiff 2

### PR DESCRIPTION
**Pull request by Glavin001**
### What does this implement/fix? Explain your changes.

Update prettydiff dependency from version 1.16.37 to 2.2.3.

### Does this close any currently open issues?

Closes https://github.com/Glavin001/atom-beautify/issues/881

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [x] Regenerate documentation with `npm run docs`
- [x] Add change details to `CHANGELOG.md` under "Next" section
- [ ] Added examples for testing to [examples/ directory](examples/)
- [x] Travis CI passes (Mac support)
- [x] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by szeck87** [comment]
Does UX Markup need to be moved under xml language?  https://github.com/Glavin001/atom-beautify/blob/153a5072905b4ea6d14960886eaeddd594bf6265/src/beautifiers/prettydiff.coffee#L96

**Comment by Glavin001** [comment]
> Does UX Markup need to be moved under xml language?

Need to test at http://prettydiff.com/

**Comment by szeck87** [comment]
I ran `atom --test spec/beautify-languages-spec.coffee` with and without that change, and it seemed to work.

**Comment by Glavin001** [comment]
So looks like either works. We can keep it as is then. Change in the future if @prettydiff recommends us doing so or if there is a bug from a user.

**Comment by szeck87** [comment]
No sorry, only xml worked, html failed.

**Comment by szeck87** [comment]
Also, is 2.2.3 still the desired version?

**Comment by Glavin001** [comment]
> No sorry, only xml worked, html failed.

It is currently failing and being treated as `html`. So if I switch to `xml` then it will pass? :+1: Great news! Thanks for testing! 

> Also, is 2.2.3 still the desired version?

Good eye. Looks like `2.2.7`: https://www.npmjs.com/package/prettydiff2

**Comment by szeck87** [comment]
All green!

**Comment by Glavin001** [comment]
Great team work, @szeck87 and @prettydiff ! This has been a long time coming and very exciting. I'm sure a lot of users will be very happy with this upcoming release.

**Comment by Glavin001** [comment]
Published to v0.30.6

**Pull request merged**
