### PR TITLE
Python: formater->formatter

### PR DESCRIPTION
**Pull request by nathdwek**
Fix an annoying typo spread around in the python beautifier.
This would the config of existing users. I don't know what your policy is on this.

### CODE REVIEW

**Comment by derwiki** [comment]
+1

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.32.0

**Comment by nathdwek** [comment]
While you're on this, could you maybe take a look at #1897, which is probably the more interesting of the two?

**Comment by Glavin001** [comment]
Thanks for the notice @nathdwek . I missed #1897. I'll try to get it in the next release 😄

**Pull request merged**
