### PR TITLE
Support stylish-haskell

### PR DESCRIPTION
**Pull request by bobjflong**
fixes https://github.com/Glavin001/atom-beautify/issues/628

### CODE REVIEW

**Comment by Glavin001** [comment]
This is great!

Could you also add a simple test example file and run the command `Window: Run package spec`. See step 4 from `How to add a Beautifier for a Language`: https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language

You may have to edit [`.travis.yml`](https://github.com/Glavin001/atom-beautify/blob/master/.travis.yml#L30) and [`.appyveyor.yml`](https://github.com/Glavin001/atom-beautify/blob/master/appveyor.yml#L43) so the tests pass when run on CI.

**Comment by bobjflong** [comment]
@Glavin001 I've added a test case. However I think that the only real way to install `stylish-haskell` is via Haskell source, so it might be more trouble than it's worth to get this working with CI :/

**Comment by Glavin001** [comment]
> I've added a test case. 

Thanks!

> However I think that the only real way to install stylish-haskell is via Haskell source, so it might be more trouble than it's worth to get this working with CI :/

Bummer. If you can get it working on Travis CI that would be great -- I find Windows with AppVeyor to be too difficult to get working sometimes anyway, so Travis CI (Linux) is my Go-To CI for verifying Pull Requests.

If you are unable to get Travis CI working, then change the `original/test.hs` to `original/_test.hs` which will disable that test (tests with `_` prefix are ignored).

After that, I can merge this as is.

Thank you for contributing!

**Comment by bobjflong** [comment]
I got travis to pass! Installing the hs dependencies adds to the travis build time but that's probably OK?

**Comment by Glavin001** [comment]
Absolutely OK. This is great! Thank you for contributing.

**Comment by Glavin001** [comment]
Published to v0.28.16

**Comment by bobjflong** [comment]
:beers:

**Pull request merged**
