### PR TITLE
Add GN beautifier

### PR DESCRIPTION
**Pull request by samogot**
### What does this implement/fix? Explain your changes.

Add GN language and beautifier

### Does this close any currently open issues?

No

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [x] Regenerate documentation with `npm run docs`
- [x] Add change details to `CHANGELOG.md` under "Next" section
- [x] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by Glavin001** [comment]
Published to v0.32.0

**Comment by szeck87** [comment]
@samogot is the only way to install depot_tools through cloning the repo and adding to your path?

**Comment by samogot** [comment]
@szeck87 It is the most documented way. If someone use GN he will have GN binary somehow, most of GN users are chromium contributors, so they will gen GN this way.
In our project (not related to chromium) we just have gn binary in our git repo, but it can't be suggested as install instructions, because you will anyway need depot_tools and chromium repo to get gn binary for the firs time

**Comment by szeck87** [comment]
@samogot ok thanks.  I'm trying to fix the CI build, when updating the path what does it need to be exactly?

**Pull request merged**
