### PR TITLE
Add JSCS Fixer

### LINKED ISSUE #286: Add importer linter-jscs
I can`t understand how to beautify works with linter-jscs  presets.
Atom - 0.188.0
atom-beautify options:
  Beautify On Save - on.
  Beautify Entire File On Save - on.
linter-jscs options:
  Preset: yandex

Now animations what happens:
output_2b3e4o

All that means that beautify dismiss all changes that I do with linter-jscs hints. Please help to fix a problem. Thank you.

### PR DESCRIPTION
**Pull request by Cortys**
Fixes #286.

Just a minimal implementation. Could still be improved:

- Cannot be configured via the settings UI yet.
- Only fixes files, that have a .jscsrc file in one of their parent
folders (up to the project root folder in Atom).

### CODE REVIEW

**Comment by Glavin001** [comment]
Looks good. Please merge the latest upstream changes that fixes the CI errors and then this PR should pass all of the tests and be ready for merging. Thanks!

**Comment by Cortys** [comment]
Changes are merged now.

The AppVeyor failure isn't related to the pull request (apparently Atom installation failed).

**Comment by Cortys** [comment]
Fixed now.

**Comment by Glavin001** [comment]
Looks good! Thank you!

**Comment by Glavin001** [comment]
Published to v0.28.7

**Pull request merged**
