### PR TITLE
Add JSX option to to JS Beautify

### PR DESCRIPTION
**Pull request by NodeJoSe**
### What does this implement/fix? Explain your changes.

I would love to use the **language-babel** syntax package and **JS Beautify** together for my **js** files, this will make it possible!

### CODE REVIEW

**Comment by Glavin001** [comment]
`.js` files are not `.jsx` (JSX) files. Can you provide more information about this?
However, it looks like `JS Beautify` does support JSX syntax: https://github.com/beautify-web/js-beautify/issues/425#issuecomment-91025201
My main concern is allowing users to use `JS Beautify` and have it break their `JSX` code.

**Comment by NodeJoSe** [comment]
**Lenguaje-Babel** is a package to add syntax highlight to JS files for JavaScript ES201x, plus React JSX files, i was using it to get better syntax on my js files using some es6 features, but i wont be able to use JS Beautify because it add a new gramar to my **JS** files "**Babel ES6 JavaScript**"

Maybe its better just to add that gramar to the JS Beautify options, and not the whole JSX, it is possible?

**Comment by NodeJoSe** [comment]
ill remake this pull request on the master branch too, sorry about that

**Comment by Glavin001** [comment]
Published to v0.29.15

**Pull request merged**
