### PR TITLE
Added option for sqlformat to re-indent

### PR DESCRIPTION
**Pull request by faheel**
### What does this implement/fix? Explain your changes.

Added an option to either re-indent code or to preserve indentation. The SQL formatter, sqlparse, has an option for exactly this and is useful when the indentation is to be left unchanged.

### Does this close any currently open issues?

No.

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [x] Regenerate documentation with `npm run docs`
- [x] Add change details to `CHANGELOG.md` under "Next" section
- [ ] Added examples for testing to [examples/ directory](examples/)
- [x] Travis CI passes (Mac support)
- [x] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by faheel** [comment]
Working on completing the checklist...

**Comment by faheel** [comment]
@Glavin001 Do I need to add examples for this new option?

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.32.0

**Pull request merged**
