### PR TITLE
Add PrettyDiff's bracepadding support

### PR DESCRIPTION
**Pull request by qwemaze**
See #1157

### CODE REVIEW

**Comment by Glavin001** [comment]
The failing tests are unrelated.

Please add the new documentation and I can merge. Thank you!

P.S. Here's how to update docs:

```bash
npm run postinstall
npm run docs
```

**Comment by qwemaze** [comment]
Docs updated

**Comment by Glavin001** [comment]
Looks good to me. Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.29.12

**Pull request merged**
