### PR TITLE
Added opencl language support

### PR DESCRIPTION
**Pull request by MichaelHancock**
### What does this implement/fix? Explain your changes.

Added support for opencl language by including its file extension .cl in the c language support module.

### Does this close any currently open issues?

https://github.com/Glavin001/atom-beautify/issues/870

### Any other comments?

OpenCL language support is achieved here simply by attaching '.CL' extension to the 'C' language module. OpenCL is C based however beautify will not support beautification despite having C language support, due to the different file extension.

### CODE REVIEW

**Comment by Glavin001** [comment]
Could you add an example OpenCL file with the extension `.cl` to test? Thanks.

**Comment by MichaelHancock** [comment]
Without wanting to sound like an absolute noob. Im not 100% sure to do that? I have opencl files available, but have never used these auto tests before. Sorry...

**Comment by Glavin001** [comment]
No problem.

See step 4 of `How to add a Beautifier for a Language`: https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language 

Basically, add a directory `OpenCL` and two directories `original` and `expected` with files:
- original file like you have
- expected file is the expected result after beautification

**Comment by Glavin001** [comment]
Published to v0.28.28

**Comment by Glavin001** [comment]
Marking as duplicate of #872 (which was actually merged).

**Pull request closed without merging**
