### PR TITLE
Add Optional Path for Rubocop

### PR DESCRIPTION
**Pull request by emanuelet**
add option to specify the path for rubocop in the settings.
The relative beautifier now retrieve the path similarly to how the php-cs-fixer one does.

I tested it and is working correctly on my system.

### CODE REVIEW

**Comment by emanuelet** [comment]
apparently the appveyor build is failing generating documentation, or so it seems. Is it safe to ignore?

**Comment by Glavin001** [comment]
I will ignore the AppVeyor tests. 

Could you run "coffee docs/" to build the documentation with the new option and commit that change with this pull request? Looks about ready to merge. Thanks!

**Comment by emanuelet** [comment]
done

**Comment by Glavin001** [comment]
Awesome. Great work! Thank you so much for contributing!

**Comment by emanuelet** [comment]
my pleasure

**Comment by emanuelet** [comment]
hi, can I ask you if you can push a new minor release?

**Comment by Glavin001** [comment]
Published to v0.28.20
Thanks

**Comment by emanuelet** [comment]
thank you very much

**Pull request merged**
