### PR TITLE
Add .php_cs file support to php-cs-fixer beautifier

### PR DESCRIPTION
**Pull request by sharifzadesina**
### What does this implement/fix? Explain your changes.

Add .php_cs file (php-cs-fixer config file) support to php-cs-fixer beautifier.
...

### Does this close any currently open issues?

Yes, #564 
...

### Any other comments?

1- I was added a `findFile` method, i think we can use this method in other beautifiers which support config file (e.g. rustfmt beautifier).
2- I think will be better if you chose a same coding style guild for all coffee files.
...

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by Glavin001** [comment]
Thanks for contributing! Before I can merge, please resolve the Travis CI failing tests: https://travis-ci.org/Glavin001/atom-beautify/jobs/136434683
Thanks!

**Comment by sharifzadesina** [comment]
I think you can fix this now.

**Comment by Glavin001** [comment]
Awesome. Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.29.8

**Pull request merged**
