### PR TITLE
Fix #1790. Fix Lua indentation format bug

### LINKED ISSUE #1790: LUA beautifier can't deal with escape brackets
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```Lua
Stautsbar = {
  Blank = [[Interface\BUTTONS\WHITE8X8.blp]]
}

        local L = 123
local x = 1
```

# Expected Output

The beautified code should have looked like this:

```Lua
Stautsbar = {
  Blank = [[Interface\BUTTONS\WHITE8X8.blp]]
}

local L = 123
local x = 1
```

# Actual Output

The beautified code actually looked like this:

```Lua
Stautsbar = {
  Blank = [[Interface\BUTTONS\WHITE8X8.blp]]
}

        local L = 123
local x = 1

```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist:  https://gist.github.com/babbelnedd/b277aed05f971bd1d6a72a9a88628d8a

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

### PR DESCRIPTION
**Pull request by hxsf**
### What does this implement/fix? Explain your changes.
fix lua format bug about indent
### Does this close any currently open issues?
#1790 

### Any other comments?

can update dependencies? it still need node 0.8.x, it is too old.

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [ ] Regenerate documentation with `npm run docs`
- [ ] Add change details to `CHANGELOG.md` under "Next" section
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by szeck87** [comment]
@hxsf should this line only be indented with two spaces with this fix?  https://github.com/Glavin001/atom-beautify/blob/master/examples/simple-jsbeautifyrc/lua/expected/test.lua#L22

**Comment by hxsf** [comment]
@szeck87 yes, this format will not change any `block comments` or `multi-line string` to keep the indent, space in these blocks.

**Comment by szeck87** [comment]
@hxsf yea https://github.com/Glavin001/atom-beautify/blob/master/examples/simple-jsbeautifyrc/lua/expected/test.lua#L22 is being changed from `    --[[` to `  --[[` (4 spaces to 2 spaces) with your changes.  Please update that file.

**Comment by Glavin001** [comment]
Thank for your contributing, @hxsf !

**Comment by Glavin001** [comment]
Published to v0.32.2

**Pull request merged**
