### PR TITLE
Add option to disable the loading notification && Add pybeautifier

### LINKED ISSUE #585: Add option to disable the loading notification
Could there be an option in the settings disable to notification that says "Beautification in Progress"? Don't see the need to show this each time if using Beautify on save.

### PR DESCRIPTION
**Pull request by guyskk**
### What does this implement/fix? Explain your changes.

Add option to disable the loading notification

### Does this close any currently open issues?

https://github.com/Glavin001/atom-beautify/issues/585

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by guyskk** [comment]
Add pybeautifier, see https://github.com/guyskk/pybeautifier

**Comment by Alhadis** [comment]
@Glavin001 I already blocked that stupid @mention-bot, how the hell was it able to send me a notification? :|

FFS, bot

**Comment by Glavin001** [comment]
@Alhadis feel free to submit a PR adding yourself to https://github.com/Glavin001/atom-beautify/blob/master/.mention-bot#L4
Sorry it's been bugging you!

**Comment by Alhadis** [comment]
Your bot may be doing more harm then good. If I see a notification originating from this repository, I'm now inclined to ignore it. If other casual contributors respond the same way, it'll be harder to collect meaningful feedback when it actually becomes warranted.

**Comment by Glavin001** [comment]
> Your bot 

It is a Facebook bot: https://github.com/facebook/mention-bot 😉 

> may be doing more harm then good...

I absolutely agree. I have temporarily disabled the webhook until I can spend the time to configure it more appropriately. Thank you for your feedback!

**Comment by guyskk** [comment]
@Glavin001 Hi, I have used this branch a month and it didn't appear any problem. If unit tests are needed, I can add some tests. And this branch has conflicts with master, do you need any help? I'm waiting for merging.

**Comment by Glavin001** [comment]
Hi @guyskk I've just finished my final exams yesterday and should now have more time to revisit Atom-Beautify and get these Pull Requests reviewed and merged. Thanks for your patience!

**Comment by rogaha** [comment]
Please ignore my LGTM, I was just checking if I had the permission to review! :) The feature is much appreciated though!

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.29.19

**Pull request merged**
