### PR TITLE
update prettydiff dependency version to 1.16.1

### PR DESCRIPTION
**Pull request by EisFrei**

### CODE REVIEW

**Comment by Glavin001** [comment]
@prettydiff there appears to be errors with the latest version. See https://travis-ci.org/Glavin001/atom-beautify/builds/96941564 Could you take a look?

Example:

```
BeautifyLanguages
  when using configuration 'nested-jsbeautifyrc'
    when beautifying language 'html-erb'
      it test test.erb
        Expected true not to equal true, { code : 'MODULE_NOT_FOUND' }.
          at completionFun (/Users/travis/build/Glavin001/atom-beautify/spec/beautify-languages-spec.coffee:159:61)
          at tryCatcher (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/util.js:26:23)
          at Promise._settlePromiseFromHandler (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/promise.js:507:31)
          at Promise._settlePromiseAt (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/promise.js:581:18)
          at Promise._settlePromises (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/promise.js:697:14)
          at Async._drainQueue (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/async.js:123:16)
          at Async._drainQueues (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/async.js:133:10)
          at MutationObserver.Async.drainQueues (/Users/travis/build/Glavin001/atom-beautify/node_modules/bluebird/js/main/async.js:15:14)

```

**Comment by prettydiff** [comment]
NPM goofed and so I bumped to version 1.16.2.

https://github.com/prettydiff/prettydiff/issues/237

**Comment by Glavin001** [comment]
Thanks. I restarted the Travis CI build to see if it is fixed now.

**Comment by Glavin001** [comment]
I updated the Prettydiff version to 1.6.15

**Pull request closed without merging**
