### PR TITLE
Update typescript-formatter and add tsx support

### PR DESCRIPTION
**Pull request by szeck87**
### What does this implement/fix? Explain your changes.
Updates typescript-formatter to latest version, along with necessary change in coffeescript file. Also adds support for TSX language and typescript-formatter ability to format it.
...

### Does this close any currently open issues?
#601 #1977
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [X] Merged with latest `master` branch
- [X] Regenerate documentation with `npm run docs`
- [X] Add change details to `CHANGELOG.md` under "Next" section
- [x] Added examples for testing to [examples/ directory](examples/)
- [X] Travis CI passes (Mac support)
- [X] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by nicodmf** [comment]
@Glavin001  Please add a version with this :)

**Comment by Glavin001** [comment]
I should publish this weekend. I want to merge a few more Pull Requests and need some more time to review 😃 . Thank you for your reminder and interest! I will post here once I've published the next release.

**Comment by Glavin001** [comment]
Published to v0.32.0

**Comment by nicodmf** [comment]
Thanks :)

**Pull request merged**
