### PR TITLE
Implement a basic beautifer for Vue Components

### LINKED ISSUE #722: Add Language Support for Vue component files.
Please see http://vuejs.github.io/vue-loader/start/spec.html for a spec on vue files.

Basic premise is its an XML/HTML file that can contain Javascript, Coffee script, Less, Sass or Stylus.
For now I can make use of linking components to source files, but would be nice to have support for Vue files themselves.

### PR DESCRIPTION
**Pull request by aidistan**
### What does this implement/fix? Explain your changes.

- Add a language `vue`
- Add a beautifier `vue-beautifier`
- Fix AppVeyor CI temporally

---

### Does this close any currently open issues?

Related to #1119 and LeslieYQ/vue-format#1, close #722

---

### Any other comments?

Nope

---

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [x] Added examples for testing to [examples/ directory](examples/)
- [x] Travis CI passes (Mac support)
- [x] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by prettydiff** [comment]
This is far more complete than the pull request I submitted.

**Comment by aidistan** [comment]
I have fixed AppVeyor CI temporally by [skipping `ocaml` test in Windows](https://github.com/aidistan/atom-beautify/blob/33cec49851876847fb4c57a34705eff1112b9caa/spec/beautify-languages-spec.coffee#L98). Hope someone could find a way to install `ocp-indent` and make that test brought in by #934 work.

**Comment by aidistan** [comment]
I have completed the checklist. @prettydiff what else could I do for this PR? @Glavin001 any comment or suggestion on this PR?

**Comment by Glavin001** [comment]
Looking good at first glance!

I just got back from vacation and now have a final exam coming up. I hope to review, merge, and publish this on (or before) Monday night.

**Comment by Glavin001** [comment]
It's a great start to a Vue beautifier, so I've merged it. Thanks for making all tests pass! I will be publishing after I have time to merge all of the other Pull Requests. Thank you for contributing!

**Comment by devboxr** [comment]
Thanks everybody. Just just made a lot of Vue.js developers very happy.

Keep up the good work!

**Comment by jwhitmarsh** [comment]
Is there anyway to install atom-beautify to have this right now?

**Comment by aidistan** [comment]
@jwhitmarsh Use `apm install Glavin001/atom-beautify` to install this edge version

**Comment by Glavin001** [comment]
Published to v0.29.11

**Pull request merged**
