### PR TITLE
Set ignoreResponseCode to true in yapf.coffee

### PR DESCRIPTION
**Pull request by pvomelveny**
Addressing issue [#669](https://github.com/Glavin001/atom-beautify/issues/669). Tested, and confirmed working!

### CODE REVIEW

**Comment by Glavin001** [comment]
Could you merge with the latest `master`? It should resolve the current Travis CI problems.

**Comment by pvomelveny** [comment]
Passes Travis now. No luck with AppVeyor, though it's unclear to me if the fault for that resides in the code. It seems to be hung up on something else.

**Comment by Glavin001** [comment]
Excellent. Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.28.20

**Pull request merged**
