### PR TITLE
Add SVG support

### PR DESCRIPTION
**Pull request by BuZZ-dEE**
Let me know, if it is okay.

### CODE REVIEW

**Comment by Glavin001** [comment]
Looks great so far! 

Almost there:
- [ ] Add `language-svg` to `apm` packages to be installed:
  - This is so the tests pass
  - [ ] Travis CI: https://github.com/BuZZ-dEE/atom-beautify/blob/a58ebf889dd9b7a91fdd05e97e21aab8ae9b317f/.travis.yml#L22
  - [ ] AppVeyor: https://github.com/BuZZ-dEE/atom-beautify/blob/a58ebf889dd9b7a91fdd05e97e21aab8ae9b317f/appveyor.yml#L115
- [ ] Add `svg` to `keywords` in the `package.json`
 
Thanks!

**Comment by BuZZ-dEE** [comment]
Thanks for your quick reply. I think, it is done now. Please let me now, if you have a further remark.

**Comment by Glavin001** [comment]
Right on! All tests passing and linted. Thank you for your contribution!

**Comment by Glavin001** [comment]
Published to v0.28.8

**Pull request merged**
