### PR TITLE
[PrettyDiff] Fixed Indent Tabs configuration ignored (issue: #910: ht…

### PR DESCRIPTION
**Pull request by ayoubdev**
### What does this implement/fix? Explain your changes.

Fixes: PrettyDiff configuration: Indent Tab getting ignored 

### Does this close any currently open issues?

Closes issue #910 

### Any other comments?

No

### CODE REVIEW

**Comment by prettydiff** [comment]
Just to keep everybody informed after this next week I will be offline for 6 weeks while at the Army Warrant Officer Candidate School.

**Comment by Glavin001** [comment]
@ayoubdev could you also run `npm run docs` to generate the updated documentation for these option changes? Besides that, it looks good to merge! Thanks!

**Comment by ayoubdev** [comment]
@Glavin001 Done.

**Comment by Glavin001** [comment]
Thanks for contributing!

**Comment by Glavin001** [comment]
Published to v0.29.7

**Pull request merged**
