### PR TITLE
Updated options for js-beautify

### PR DESCRIPTION
**Pull request by filipesilva**
Been waiting for this moment for a couple of weeks now. This new option will finally let me have my angular html templates formatted the way I want, with one attribute per line.

### CODE REVIEW

**Comment by filipesilva** [comment]
Sec, fixing some broken tests.

**Comment by filipesilva** [comment]
Unbumped the version number.

**Comment by Glavin001** [comment]
Great, thanks! I'll be back in an hour or so and test this Pull Request, merge, and publish.

**Comment by filipesilva** [comment]
Thank you :D

**Comment by Glavin001** [comment]
Published to v0.21.4

Thank you for contributing!

**Pull request merged**
