### PR TITLE
Fix incorrect name for pandoc path option

### PR DESCRIPTION
**Pull request by KoharaKazuya**
"Markdown pandoc path" option is not working.

### CODE REVIEW

**Comment by Glavin001** [comment]
You're right! 
See code at: https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L263

Could you make the tests pass. Just need to change https://github.com/KoharaKazuya/atom-beautify/blob/2fe815e47cf8c95d099ee0f17b2c4d83dc8dd2ce/lib/langs/markdown-beautify.coffee#L13 to `if not pandocPath` because the default value is `""` (empty string, see https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L265 ) not `undefined or null`.
That should fix it and then I can merge.

Thanks you!

**Comment by KoharaKazuya** [comment]
Sorry, I have no idea why test failed.

**Comment by Glavin001** [comment]
Looks, to me, like Travis CI broke :stuck_out_tongue_winking_eye: . I restarted it. Thanks!

**Comment by Glavin001** [comment]
Taking a look at this now. Looks like the failing test is with SQL beautification, not with your pull request. I hope to merge this soon. Thanks!

**Comment by Glavin001** [comment]
Published to v0.24.1

**Pull request merged**
