### PR TITLE
Added pretty diff ternaryline option - Issue 524

### PR DESCRIPTION
**Pull request by joshholl**
Added ternaryline option from pretty diff and corresponding documentation.

### CODE REVIEW

**Comment by prettydiff** [comment]
Sorry for the delay.  I am reviewing your pull request right now.  I see that both JS Beautify and Pretty Diff are supported beautifiers for this option, but only the prettydiff.coffee file was modified to support this feature.

Does JS Beautify support this feature and if so does any additional code need to be changed to make this feature available to JS Beautify?  If JS Beautify does not support this enhancement it might be better to remove that beautifier from supporting this feature until they are ready.

**Comment by jackocnr** [comment]
This is great! Do you know when this will be released? Thank you.

**Comment by Glavin001** [comment]
Published to v0.28.23

**Comment by jackocnr** [comment]
Thanks that's now working (using "preserve_ternary_lines" in my `.jsbeautifyrc` file). I'm now having some other problems, but I'll open a separate issue for that.

**Comment by joshholl** [comment]
Thanks for the work on this, sorry i hadn't had a chance to respond to earlier messages.

**Pull request merged**
