### PR TITLE
Fix deprecation warnings triggered by TextEditor methods

### PR DESCRIPTION
**Pull request by Alhadis**
Repeat of #843.

### CODE REVIEW

**Comment by Alhadis** [comment]
@Glavin001 Tests are still failing, but they don't seem related to this.

**Comment by Glavin001** [comment]
That's my fault, actually the `better-settings` branch should have been merged. I'll take care of that. Merging this now. Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.29.0

**Comment by Alhadis** [comment]
My pleasure! =)

**Pull request merged**
