### PR TITLE
Fix remark6.0.1

### LINKED ISSUE #1196: Cannot read property 'error' of undefined
I'm trying to beautify my markdown but I get the error saying "Cannot read property 'error' of undefined"

'atom' version: 1.10.2
'atom-beautify' version: 0.29.12

Error Info: 
Cannot read property 'error' of undefined
TypeError: Cannot read property 'error' of undefined
  at /Users/sun/.atom/packages/atom-beautify/src/beautifiers/remark.coffee:42:10
  at Promise._execute (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:299:9)
  at Promise._resolveFromExecutor (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:481:18)
  at new Promise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
  at Remark.module.exports.Remark.beautify (/Users/sun/.atom/packages/atom-beautify/src/beautifiers/remark.coffee:36:16)
  at /Users/sun/.atom/packages/atom-beautify/src/beautifiers/index.coffee:316:24
  at Promise._execute (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:299:9)
  at Promise._resolveFromExecutor (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:481:18)
  at new Promise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
  at /Users/sun/.atom/packages/atom-beautify/src/beautifiers/index.coffee:238:18
  at tryCatcher (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
  at Promise._settlePromise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
  at Promise._settlePromise0 (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
  at Promise._settlePromises (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
  at Promise._fulfill (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
  at PromiseArray._resolve (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
  at PromiseArray._promiseFulfilled (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
  at Promise._settlePromise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
  at Promise._settlePromise0 (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
  at Promise._settlePromises (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
  at Promise._fulfill (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
  at Promise._resolveCallback (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:431:57)
  at Promise._settlePromiseFromHandler (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:522:17)
  at Promise._settlePromise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
  at Promise._settlePromise0 (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
  at Promise._settlePromises (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
  at Promise._fulfill (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
  at Promise._resolveCallback (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:431:57)
  at Promise._settlePromiseFromHandler (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:522:17)
  at Promise._settlePromise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
  at Promise._settlePromise0 (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
  at Promise._settlePromises (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
  at Promise._fulfill (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
  at Promise._resolveCallback (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:431:57)
  at ReductionPromiseArray._resolve (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/reduce.js:61:19)
  at Promise.completed [as _fulfillmentHandler0] (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/reduce.js:122:15)
  at Promise._settlePromise (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:564:21)
  at Promise._settlePromise0 (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
  at Promise._settlePromises (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
  at Async._drainQueue (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
  at Async._drainQueues (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
  at Async.drainQueues (/Users/sun/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

### PR DESCRIPTION
**Pull request by vmuriart**
### What does this implement/fix? Explain your changes.
Updates atom-beautify to use `remark`'s new API.
...

### Does this close any currently open issues?
Fixes #1196 
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by lukehsiao** [comment]
Is it possible to have this fix published in a minor version rather than waiting to publish with v0.30.0? Thanks for all your hard work, by the way. This is one of my most heavily used packages.

**Comment by vmuriart** [comment]
2nd the minor release. For now I applied the changes locally to get it to work.

**Comment by Glavin001** [comment]
Published to v0.29.15

**Pull request merged**
