### PR TITLE
Add EJS option to JS Beautify

### PR DESCRIPTION
**Pull request by NodeJoSe**
### What does this implement/fix? Explain your changes.

...We will be able to beautify HTML (Angular) Files with JS Beautify
### Does this close any currently open issues?

...
### Any other comments?

... I didnt know if i had to put "EJS" or "HTML (Angular)" on the switch
### Checklist

Check all those that are applicable and complete.
- [ ] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by Glavin001** [comment]
Looks good. The documentation needs to be re-generated though.

**Comment by Glavin001** [comment]
Thanks for contributing!

**Comment by NodeJoSe** [comment]
Thanks to you for this amazing package!

**Comment by Glavin001** [comment]
Oh noooooo! This is the wrong branch! It should have been on `master` not `better-settings`! Could you remake this Pull Request @NodeJoSe ?

**Comment by NodeJoSe** [comment]
omw

2016-12-29 0:54 GMT-04:00 Glavin Wiechert <notifications@github.com>:

**Comment by Glavin001** [comment]
Published to v0.29.15

**Pull request merged**
