### PR TITLE
Add "F90" extension

### PR DESCRIPTION
**Pull request by smcouch**
### What does this implement/fix? Explain your changes.

This PR implements beautify compatibility with free-form Fortran files ending in ".F90".

### Does this close any currently open issues?

This resolves issue #1036.

Now works for Fortran files ending in ".F90"

### CODE REVIEW

**Comment by Glavin001** [comment]
Either this will be merged, or another small change making all extensions case insensitive. Opinions welcome 😄 .

**Comment by Glavin001** [comment]
I'm going to merge this for now and implement case-insensitivity later.

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by smcouch** [comment]
Most welcome!  atom-beautify is an excellent package.  As I come across more case-sensitivity issues, I'll fix them and send a PR.

**Comment by Glavin001** [comment]
Published to v0.29.11

**Pull request merged**
