### PR TITLE
Add ESLint beautifier

### PR DESCRIPTION
**Pull request by taylon**
Hey guys,

This is an implementation for the ESLint fixer for Javascript.
Let me know if there is any improvement that must be done before it gets merged. I have been using it for a couple of weeks and it's great.

Thanks,

### CODE REVIEW

**Comment by prettydiff** [comment]
You will need to get the travis.ci tests to pass before Glavion will merge this.  You will probably also have to create test units.

Have you checked to see which of the currently supported options are applicable to ESLint and applied then in the necessary configuration?

**Comment by taylon** [comment]
I just fixed a couple of lint errors but the travis job still does not pass, but I believe it is nothing related to the ESLint beautifier.

Regarding the configuration, I think that ESLint doesn't make much sense without it's own configuration so I went with an approach similar to the JSCS and other beautifiers which doesn't not support any configuration.

**Comment by Glavin001** [comment]
Since this is not a default beautifier for JavaScript, it will not be a breaking change to users. I don't mind merging this and letting users test this out for themselves. 

Thank you for contributing, @taylon !

**Comment by Glavin001** [comment]
Published to v0.29.18

**Pull request merged**
