### PR TITLE
Add 'Babel ES6 JavaScript' as a grammar that supports JSX.

### PR DESCRIPTION
**Pull request by gandm**
### What does this implement/fix? Explain your changes.
Adds language-babel's grammar name to JSX supported languages.
...

### Does this close any currently open issues?
No
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [ ] Merged with latest `master` branch
- [ ] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

Add support for the language-babel package.

### CODE REVIEW

**Comment by prettydiff** [comment]
Why should this grammar be associated with JSX opposed to JavaScript?  Does this directory support XML tags as language tokens?

**Comment by gandm** [comment]
The language grammar supports Facebook's JSX, which I believe this language file relates to.

**Comment by gandm** [comment]
Maybe I've misunderstood how these language files work. I'll close the PR. Thanks

**Comment by prettydiff** [comment]
@gandm I recommend reopening the pull request.  You code change is spot on and it sounds like the request is completely accurate if this Babel variant supports JSX additions.  Perhaps you misunderstood because I used the word *directory* when I meant to use the word *directly*.  Sorry, its a busy day at work.

**Comment by gandm** [comment]
@prettydiff Thanks for the info. My package, [language-babel](atom.io/packages/language-babel), is the one recommended in Facebook's nuclide project, as well as github's jsx highlighter, and I thought that adding it here would help some people who might use this package. Thinking about it, as I also support flow typing, it is probably not appropriate to fix it to a single beautifier.  

Thanks again.

**Pull request closed without merging**
