### PR TITLE
Adding language Riot.js

### PR DESCRIPTION
**Pull request by prettydiff**
Adding new language Riot.js per issues: https://github.com/Glavin001/atom-beautify/issues/731 and https://github.com/Glavin001/atom-beautify/issues/750

### CODE REVIEW

**Comment by Glavin001** [comment]
Published to v0.28.22

**Comment by emarinizquierdo** [comment]
Are you able to beautify a riotjs .tag file with this publication? Atom is telling me: 

Unknown beautification result null.
Unknown beautification result null.
Hide Stack Trace
Error: Unknown beautification result null.
  at completionFun (/home/myuser/.atom/packages/atom-beautify/src/beautify.coffee:225:24)
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
  at Promise._settlePromiseAt (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromises (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
  at Async._drainQueue (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)


Thanks!

**Comment by Glavin001** [comment]
Could someone ( @emarinizquierdo  or @prettydiff ) please submit a Pull Request for a Riotjs example that confirms this is, or is not, working? Thank you.

See step 4 of https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-beautifier-for-a-language

**Comment by prettydiff** [comment]
https://github.com/Glavin001/atom-beautify/pull/828

**Comment by Glavin001** [comment]
Confirmed the tests are failing.

I do not see `Riot.js` as a supported language with Pretty Diff. Should be found:
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L37-L56
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L67-L101

That is what was missing from this pull request.

**Comment by prettydiff** [comment]
I was just getting to tackle https://github.com/Glavin001/atom-beautify/pull/757#issuecomment-188919979 but it looks like you have accomplished this.  Is there anything further you need me to do?

**Comment by Glavin001** [comment]
It looks like the tests for LESS are failing in the latest build: https://travis-ci.org/Glavin001/atom-beautify/jobs/111920157
If you could update the LESS tests such that they do not fail with Pretty Diff that'd be great. Thanks!

And I am going to disable Haskell tests since it takes so long and Travis CI for public repos does not (yet) support caching, which would resolve this issue.

**Pull request merged**
