### PR TITLE
[#776] Bump jsbeautify to 1.6.2.  Add support for collapse-preserve-inline

### PR DESCRIPTION
**Pull request by kaaloo**
I have tested the package locally and the option seems to work fine now.

### CODE REVIEW

**Comment by lnewman-book** [comment]
Failed tests?

**Comment by prettydiff** [comment]
Yeah, the unit tests appear to need some work.

**Comment by lnewman-book** [comment]
Could I ask that you hold off on this for today?  There's been a request for moving `preserve-inline` to a separate setting to allow it to be combined with `expand` and `end-expand`.  If that happens, it would cause churn in this area.  Let me see how difficult that would be.

**Comment by bitwiseman** [comment]
Please hold of on this for today.  Looking at options making this option less disruptive.

**Comment by bitwiseman** [comment]
Hmm, never mind.  I don't have the bandwidth for further changes at this time.

**Comment by kaaloo** [comment]
Yup, probably because of the jsbeautify version bump.

**Comment by ttsirkia** [comment]
+1 for this. It would be great to finally get this particular feature.

**Comment by NerdPad** [comment]
+1 if we can get this feature.

**Comment by kaaloo** [comment]
Thank you that's awesome!

**Comment by Glavin001** [comment]
Published to v0.28.23

**Comment by ttsirkia** [comment]
After a short experiment, it seems that objects are sitll expanded to multiple lines as before although this new option is selected. Can someone else share experiences?

**Comment by Glavin001** [comment]
@ttsirkia please create a new issue and follow the instructions provided in the template. Thank you.

**Comment by ttsirkia** [comment]
Sure, #831. I was just asking if someone could give a quick comment if there is only something wrong in my environment.

**Pull request merged**
