### PR TITLE
Add MagicPython grammar to python language

### PR DESCRIPTION
**Pull request by szeck87**
### What does this implement/fix? Explain your changes.
This adds the grammar `MagicPython` to the Python language.  Any files with MagicPython will be treated as Python and beautified as such.
...

### Does this close any currently open issues?
https://github.com/Glavin001/atom-beautify/issues/1851
...

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [X] Merged with latest `master` branch
- [X] Regenerate documentation with `npm run docs`
- [X] Add change details to `CHANGELOG.md` under "Next" section
- [ ] Added examples for testing to [examples/ directory](examples/)
- [X] Travis CI passes (Mac support)
- [X] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by szeck87** [comment]
Also added `aspcud` to Linux CI installation to fix the new build issue.

**Comment by szeck87** [comment]
@Glavin001 have you had a chance to look this over?

**Comment by szeck87** [comment]
Not stale.

**Comment by Glavin001** [comment]
Published to v0.32.0

**Pull request merged**
