### PR TITLE
Default prettydiff comments to indent

### LINKED ISSUE #561: Beautifying HTML(Angular) unindents comments
Here is the gist with debug information:
https://gist.github.com/filipesilva/9d3e9a644379519e071a

Input:
```
<div>
    <div>
        <!-- comment here -->
        <div></div>
    </div>
</div>
```

Expected:
```
<div>
    <div>
        <!-- comment here -->
        <div></div>
    </div>
</div>
```

Actual
```
<div>
    <div>
<!-- comment here -->
        <div></div>
    </div>
</div>
```

If I remember correctly, the HTML (Angular) beautifying is handled by Prettydiff EJS beautifying. I tried this on Prettydiff's website and the result was the expected one, whereas on Atom I got the actual one.

Earlier today I reported an issue and you recommended me to reinstall `atom-beautify` which I have, so I don't think it's a version thing.

### PR DESCRIPTION
**Pull request by filipesilva**
Close #561

### CODE REVIEW

**Comment by Glavin001** [comment]
Thank you for contributing!

**Comment by Glavin001** [comment]
Published patch to v0.28.14

**Comment by filipesilva** [comment]
Thanks you for the awesome package. This is easily the package I use most.

**Comment by Glavin001** [comment]
You're welcome! Glad to hear it :smiley:. It would not be possible without contributors like yourself and awesome work by third-party package maintainers like @prettydiff!

**Pull request merged**
