### PR TITLE
add ocaml language

### PR DESCRIPTION
**Pull request by fdelbos**
### What does this implement/fix? Explain your changes.

Adds support for OCaml language indentation

### Does this close any currently open issues?

no

### Any other comments?

ocp-indent must be installed:
```
brew install ocaml opam
opam install ocp-indent
```

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [x] Added examples for testing to [examples/ directory](examples/)
- [ ] Travis CI passes (Mac support)
- [ ] AppVeyor passes (Windows support)

### CODE REVIEW

**Comment by Glavin001** [comment]
Published to v0.29.7

**Comment by AllanWang** [comment]
Given the checkboxes above, I presume this isn't compatible with windows?

**Comment by szeck87** [comment]
The checkboxes are for the test scripts.  It should work on Windows, I'd have to find where you can download and install OCaml/opam for Windows, give me a bit.

**Comment by AllanWang** [comment]
@szeck87 

https://fdopen.github.io/opam-repository-mingw/

It's there. But I'm not sure how to link it

**Comment by AllanWang** [comment]
@szeck87 any luck?

I've managed to install ocp-indent, but it is under `C:\OCaml64\home\[user]\.opam\4.03.0+mingw64\bin`.
`where.exe ocp-indent` will only find the path in the ocaml terminal, and not in the powershell, and as far as I'm aware, there's no location to specify file paths in beautify

**Comment by szeck87** [comment]
Sorry was working on a different issue.  Let me fire up my PC and install ocaml/opam and try.

**Comment by szeck87** [comment]
Sorry, I tried for an hour and couldn't get it.  I would reach out to the maintainers of ocaml and ask how to install it and any packages for use in Windows.

**Pull request merged**
