### PR TITLE
Link to the official PHP-CS-Fixer repository

### PR DESCRIPTION
**Pull request by SpacePossum**
Linking to the installation instructions of PHP doens't really help people when working the PHP-CS-Fixer :)

### CODE REVIEW

**Comment by Glavin001** [comment]
The README.md is actually automatically generated, so your changes would be deleted soon 😉 .

However, I do agree we need to update the documentation! Here is where the change needs to happen: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L12
Then `npm run docs` to generate the updated documentation.
Thanks!

**Comment by SpacePossum** [comment]
Thank you for the reply

>npm run docs

```
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
```

(after `npm -i`)
Maybe you can pick my commit on a new branch from master and generate the docs, squash those commit with you as author and merge it to master? :)

**Comment by Bana0615** [comment]
i keep getting Could not find 'php-cs-fixer'. The program may not be installed. when i save php files. What do i have to link to so this will work?

**Comment by Glavin001** [comment]
@Bana0615 the link is: https://github.com/FriendsOfPHP/PHP-CS-Fixer
I recommend looking at https://github.com/Glavin001/atom-beautify/search?q=Could+not+find+%27php-cs-fixer%27&state=closed&type=Issues&utf8=%E2%9C%93 if you still have issues.

---

@SpacePossum : Actually I will merge this now and when I release next I will likely have to run `npm run docs` myself before publishing, thus updating the docs for you 😃.

**Comment by SpacePossum** [comment]
@Glavin001 thank you! :+1: :)

**Comment by Glavin001** [comment]
Thank you, @SpacePossum, for contributing! 😄

**Comment by Glavin001** [comment]
Published to v0.29.15

**Comment by Bana0615** [comment]
@Glavin001 Where should i put the link? "https://github.com/FriendsOfPHP/PHP-CS-Fixer" so i can us it?

**Comment by Bana0615** [comment]
@Glavin001 i have PHP-CS-Fixer installed as a package and i still get the same error "Could not find 'php-cs-fixer'. The program may not be installed." Do i still need to add the link "https://github.com/FriendsOfPHP/PHP-CS-Fixer" some where?

**Comment by Glavin001** [comment]
@Bana0615 You should verify you correctly installed PHP-CS-Fixer on your machine and use the `Atom-Beautify: Help Debug Editor` command within Atom to generate some debugging information  which may help you.

**Pull request merged**
