### PR TITLE
Added support for Marko templates.

### PR DESCRIPTION
**Pull request by peterdotjs**
#218

### CODE REVIEW

**Comment by Solido** [comment]
Great !

**Comment by peterdotjs** [comment]
@Glavin001 I'm not sure why it's failing, looks like tests are expecting an extra line break at the end.

**Comment by Glavin001** [comment]
There's an extra newline:

```
Expected '<if test="data.items">
  <for each="item in data.items">
    <div>${item.name}</div>
  </for>
</if>
<else>
  content
</else>' to equal '<if test="data.items">
  <for each="item in data.items">
    <div>${item.name}</div>
  </for>
</if>
<else>
  content
</else>
'.
```

Notice `</else>` versus `</else>\n` (extra newline). I noticed Atom has been doing this, so I've been using the Right-click on the file in the tree and "Beautify File" instead, which does not have the Atom "bug/feature" of adding a newline at the end of file.

**Comment by peterdotjs** [comment]
Thanks for confirming. Fixed test case.

**Comment by Glavin001** [comment]
Awesome work!

**Comment by Solido** [comment]
Fast ...

**Comment by patrick-steele-idem** [comment]
Nice! Thanks, all! I look forward to taking advantage of this new feature and will share with others.

On a related note, I'm not a fan of Atom inserting a new line automatically so I added the following setting to my Atom config:

```
  whitespace:
    ensureSingleTrailingNewline: false
```

**Comment by Glavin001** [comment]
@patrick-steele-idem the automatic insertion of whitespace has been an issue for me as well. Thanks for sharing! Just to confirm, should that config go in Atom's `config.cson` under `editor` section, or only under the `"*"`? I'd like to apply this also.

For instance:

```cson
"*":
  editor:
    showInvisibles: true
    showIndentGuide: true
    preferredLineLength: 79
    tabLength: 4
    invisibles: {}
    # ADD THIS HERE ?
    # under `editor` section
    whitespace:
        ensureSingleTrailingNewline: false
```

**Comment by patrick-steele-idem** [comment]
@Glavin001, here's my `config.cson` for more clarity:

```coffee
"*":
  editor:
    autoIndentOnPaste: false
    preferredLineLength: 120
    tabLength: 4
    invisibles: {}
    fontSize: 17
  welcome:
    showOnStartup: false
  linter:
    showGutters: false
    showErrorInline: true
    statusBar: "None"
  whitespace:
    ensureSingleTrailingNewline: false
  "tree-view":
    hideVcsIgnoredFiles: false
    hideIgnoredNames: true
  core: {}
  emmet: {}
``` 

Oddly, it is not nested under the `editor` section...

**Comment by Glavin001** [comment]
For future reference, I believe this was published to v0.21.4

**Comment by patrick-steele-idem** [comment]
Awesome. Thanks for the update, @Glavin001, and thank you for the quick! I just tried it out on a Marko template and it worked great.

**Pull request merged**
