### PR TITLE
running provided emacs binary directly instead of running it via pyth…

### PR DESCRIPTION
**Pull request by janmolnar**
### What does this implement/fix? Explain your changes.

- allows to specify a custom path for the emacs binary on windows
- listens to emacs return codes for better error handling

### Does this close any currently open issues?

- #890

### Any other comments?

...

### Checklist

Check all those that are applicable and complete.

- [x] Merged with latest `master` branch
- [x] Added examples for testing to [examples/ directory](examples/)
- [x] Travis CI passes (Mac support)
- [x] AppVeyor passes (Windows support)

…on which does not work well on windows.

listening to emacs return codes.

### CODE REVIEW

**Comment by janmolnar** [comment]
Travis CI seems to fail because of an certificate issue. I do not completely understand the issue of AppVeyor? Is it trying to print an error message and then failing in the emitObject method?

**Comment by Glavin001** [comment]
I usually ignore AppVeyor. Windows always proves to be a huge PITA.
If Travis CI passes I will accept this Pull Request. 

I recommend running your Fortran spec locally and see if you can fix it.

**Comment by janmolnar** [comment]
Travis is passing

**Comment by janmolnar** [comment]
Unfortunatelly, I could not fix AppVeyor's problem with finding uncrustify (which is on the path)

**Comment by janmolnar** [comment]
Travis and AppVeyor are passing now

**Comment by Glavin001** [comment]
This is excellent! Thank you very much for your contribution, @janmolnar !

**Comment by Glavin001** [comment]
Published to v0.29.2

**Pull request merged**
