### PR TITLE
added import sorting using isort + small yapf fix

### PR DESCRIPTION
**Pull request by markbaas**
isort is a very useful tool that orders imports. I added the feature to both python formatters.

+ added a ignoreReturnCode: true to yapf run command to fix the empty error I was getting.

### CODE REVIEW

**Comment by Glavin001** [comment]
Looks good. Waiting to confirm the Travis CI tests pass, and then I will merge. Thank you very much!

**Comment by markbaas** [comment]
AppVeyor build details give a ruby error :/ doesn't look related to my code.

**Comment by Glavin001** [comment]
I usually ignore AppVeyor. Windows installs are a PITA.

If Travis CI passes, I consider it working.

This is really just testing to see if it broken anything else. If you really want to test this code then:
- add installation of isort to Travis CI: https://github.com/Glavin001/atom-beautify/blob/master/.travis.yml#L31
- add another example in https://github.com/Glavin001/atom-beautify/tree/master/examples for the applicable language directories and for this PR add a `.jsbeautifyrc` file with the isort option enabled (since it is disabled by default).

**Comment by Glavin001** [comment]
Could you merge with the latest `master`? It should resolve the current Travis CI problems.

**Comment by markbaas** [comment]
Let me write those tests... it will take me a while though, little short on time these days.

**Comment by markbaas** [comment]
@Glavin001 Is the example included correctly?

**Comment by Glavin001** [comment]
Yup, looks good to me. Thank you for contributing!

**Comment by Glavin001** [comment]
If you could resolve the merge conflicts and push the changes I am ready to merge. Thanks!

**Comment by markbaas** [comment]
Hey resolved the conflicts same days ago, did you see it?

**Comment by Glavin001** [comment]
Thank you for contributing!

**Pull request merged**
